import React, { useState } from 'react';
import { TestTube2, CheckCircle2, XCircle, Sparkles, Copy, Check, Terminal } from 'lucide-react';

export default function TestingHealth({ testing = {}, apiKey }) {
  const [copiedTest, setCopiedTest] = useState(false);
  const [activeTab, setActiveTab] = useState('matrix');

  const {
    testFiles = [],
    testedCount = 2,
    missingCount = 7,
    coverageRate = 22,
    testMatrix = []
  } = testing;

  const sampleTargetedTestCode = `// Generated by CodeRadar Gemini Engine
// Targeted Jest test suite for missing authentication failure modes in src/services/authService.js

import axios from 'axios';
import { loginUser, refreshSessionToken } from '../src/services/authService.js';

jest.mock('axios');

describe('AuthService Resilience & Edge Cases', () => {
  beforeEach(() => {
    localStorage.clear();
    jest.clearAllMocks();
  });

  test('should handle network timeout (ECONNREFUSED) gracefully without crashing', async () => {
    axios.post.mockRejectedValueOnce(new Error('Network timeout'));

    const result = await loginUser('test@pulsecart.io', 'securePass123');
    // Ensure service returns structured failure or null rather than unhandled rejection
    expect(result).toBeNull();
  });

  test('should return null when empty email is submitted', async () => {
    const result = await loginUser('', 'password');
    expect(result).toBeNull();
  });

  test('should handle expired session token during refresh', async () => {
    localStorage.setItem('auth_token', 'expired-jwt-token');
    axios.post.mockRejectedValueOnce({ response: { status: 401, data: 'Token expired' } });

    const result = await refreshSessionToken();
    expect(result).toBeNull();
  });
});`;

  const handleCopyCode = () => {
    navigator.clipboard.writeText(sampleTargetedTestCode);
    setCopiedTest(true);
    setTimeout(() => setCopiedTest(false), 2000);
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div>
        <h2 className="text-xl font-bold tracking-tight text-[#E6EDF3]">Testing Health & Edge Case Matrix</h2>
        <p className="text-xs text-[#8B949E] mt-0.5">
          Evaluate tested scenarios against critical missing failure paths and generate targeted tests.
        </p>
      </div>

      {/* Metrics Row */}
      <div className="grid grid-cols-1 sm:grid-cols-4 gap-4">
        <div className="bg-[#111820] border border-[#21262D] p-4 rounded-xl">
          <span className="text-xs text-[#8B949E]">Discovered Test Suites</span>
          <div className="text-2xl font-mono font-bold text-[#E6EDF3] mt-1">
            {testFiles.length} file
          </div>
          <span className="text-[11px] font-mono text-[#8B949E]">tests/auth.test.js</span>
        </div>

        <div className="bg-[#111820] border border-[#21262D] p-4 rounded-xl">
          <span className="text-xs text-[#8B949E]">Validated Scenarios</span>
          <div className="text-2xl font-mono font-bold text-[#3FB950] mt-1">
            {testedCount} tested
          </div>
          <span className="text-[11px] text-[#3FB950]">Sunny-day paths covered</span>
        </div>

        <div className="bg-[#111820] border border-[#21262D] p-4 rounded-xl">
          <span className="text-xs text-[#8B949E]">Missing Edge Cases</span>
          <div className="text-2xl font-mono font-bold text-[#F85149] mt-1">
            {missingCount} missing
          </div>
          <span className="text-[11px] text-[#F85149]">Exceptions & timeout gaps</span>
        </div>

        <div className="bg-[#111820] border border-[#21262D] p-4 rounded-xl">
          <span className="text-xs text-[#8B949E]">Edge Case Coverage</span>
          <div className="text-2xl font-mono font-bold text-[#D29922] mt-1">
            {coverageRate}%
          </div>
          <span className="text-[11px] text-[#8B949E]">Heuristic estimate</span>
        </div>
      </div>

      {/* Testing Matrix */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        {/* Left Column: Domain Scenarios Matrix */}
        <div className="lg:col-span-6 bg-[#111820] border border-[#21262D] rounded-xl p-5 space-y-4">
          <div className="flex items-center justify-between">
            <span className="text-xs font-semibold uppercase tracking-wider text-[#8B949E]">
              Critical Scenario Matrix
            </span>
            <span className="text-[11px] text-[#8B949E]">
              Heuristic Edge-Case Analysis
            </span>
          </div>

          <div className="space-y-4">
            {testMatrix.map((domain, dIdx) => (
              <div key={dIdx} className="space-y-2">
                <h4 className="text-xs font-bold text-[#58A6FF] uppercase tracking-wide">
                  {domain.domain}
                </h4>
                <div className="space-y-1.5">
                  {domain.scenarios.map((sc, sIdx) => {
                    const isTested = sc.status === 'tested';
                    return (
                      <div
                        key={sIdx}
                        className={`p-2.5 rounded-lg border text-xs flex items-start gap-2.5 ${
                          isTested 
                            ? 'bg-[#161E27] border-[#21262D]' 
                            : 'bg-[#161E27]/50 border-[#F85149]/20'
                        }`}
                      >
                        {isTested ? (
                          <CheckCircle2 className="w-4 h-4 text-[#3FB950] shrink-0 mt-0.5" />
                        ) : (
                          <XCircle className="w-4 h-4 text-[#F85149] shrink-0 mt-0.5" />
                        )}
                        <div className="space-y-0.5">
                          <span className={`font-medium ${isTested ? 'text-[#E6EDF3]' : 'text-[#F85149]'}`}>
                            {sc.name}
                          </span>
                          <p className="text-[11px] text-[#8B949E]">
                            {sc.note}
                          </p>
                        </div>
                      </div>
                    );
                  })}
                </div>
              </div>
            ))}
          </div>

          <div className="p-2.5 rounded-lg bg-[#161E27] border border-[#21262D] text-[11px] text-[#8B949E]">
            ⚠️ Note: These scenario checks represent a heuristic edge-case assessment and do not claim 100% formal test coverage.
          </div>
        </div>

        {/* Right Column: Gemini-Generated Targeted Test Cases */}
        <div className="lg:col-span-6 bg-[#111820] border border-[#21262D] rounded-xl p-5 flex flex-col justify-between">
          <div className="space-y-3">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2 text-[#58A6FF]">
                <Sparkles className="w-4 h-4" />
                <span className="text-xs font-semibold uppercase tracking-wider">
                  Targeted Tests Suggested by Gemini
                </span>
              </div>
              <button
                onClick={handleCopyCode}
                className="text-xs px-2.5 py-1 rounded bg-[#161E27] hover:bg-[#21262D] text-[#8B949E] hover:text-[#E6EDF3] border border-[#21262D] flex items-center gap-1.5 transition"
              >
                {copiedTest ? <Check className="w-3.5 h-3.5 text-[#3FB950]" /> : <Copy className="w-3.5 h-3.5" />}
                <span>{copiedTest ? 'Copied!' : 'Copy Test'}</span>
              </button>
            </div>

            <p className="text-xs text-[#8B949E] leading-relaxed">
              Based on the detected silent error swallow in <code className="text-[#58A6FF]">authService.js:23</code>, Gemini generated targeted assertions to verify network failure resilience:
            </p>

            <div className="p-3.5 rounded-lg bg-[#0B0F14] border border-[#21262D] font-mono text-[11px] text-[#E6EDF3] overflow-x-auto max-h-[360px] whitespace-pre leading-relaxed">
              {sampleTargetedTestCode}
            </div>
          </div>

          <div className="pt-4 border-t border-[#21262D] flex items-center justify-between text-xs text-[#8B949E]">
            <span>Format: Jest / Vitest syntax</span>
            <span className="font-mono text-[11px] text-[#3FB950]">3 Edge Cases Covered</span>
          </div>
        </div>
      </div>
    </div>
  );
}
